server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            # ================= AUTH (PUBLIC) =================
            - id: user-auth
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - RemoveRequestHeader=Cookie

            # ================= USER (PROTECTED) =================
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              
                - 

            # ================= STUDENT =================
            - id: student-service
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/students/**
              
                - 

            # ================= COURSE + EXAMS =================
            - id: course-service
              uri: lb://COURSE-SERVICE
              predicates:
                - Path=/api/courses/**,/api/exams/**
            
                - 

            # ================= PORTAL =================
            - id: portal-enrollments
              uri: lb://PORTAL-API
              predicates:
                - Path=/api/portal/enrollments/**
              
                

            - id: portal-dashboard
              uri: lb://PORTAL-API
              predicates:
                - Path=/api/portal/dashboard,/api/portal/statistics/**
              

            - id: portal-aggregation
              uri: lb://PORTAL-API
              predicates:
                - Path=/api/portal/students/**,/api/portal/courses/**
           

            # ================= PORTAL HEALTH (PUBLIC) =================
            - id: portal-health
              uri: lb://PORTAL-API
              predicates:
                - Path=/api/portal/health/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

# ================= JWT =================
jwt:
  secret: education-platform-secret-key-2024-very-secure-and-long-key-minimum-256-bits
