server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # User Service - Auth (PUBLIC)
        - id: user-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        # User Service - Protected
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthenticationFilter

        # Student Service
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**
          filters:
            - JwtAuthenticationFilter

        # Course Service
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/api/courses/**, /api/exams/**
          filters:
            - JwtAuthenticationFilter

        # Portal API - Inscriptions
        - id: portal-enrollments
          uri: lb://PORTAL-API
          predicates:
            - Path=/api/portal/enrollments/**
          filters:
            - JwtAuthenticationFilter

        # Portal API - Dashboard et statistiques
        - id: portal-dashboard
          uri: lb://PORTAL-API
          predicates:
            - Path=/api/portal/dashboard, /api/portal/statistics/**
          filters:
            - JwtAuthenticationFilter

        # Portal API - Agrégation
        - id: portal-aggregation
          uri: lb://PORTAL-API
          predicates:
            - Path=/api/portal/students/**, /api/portal/courses/**
          filters:
            - JwtAuthenticationFilter

        # Portal API - Health (PUBLIC)
        - id: portal-health
          uri: lb://PORTAL-API
          predicates:
            - Path=/api/portal/health/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

# JWT Configuration
jwt:
  secret: education-platform-secret-key-2024-very-secure-and-long-key-minimum-256-bits
