server:
  port: 8083

spring:
  application:
    name: portal-api
  datasource:
    url: jdbc:mysql://localhost:3306/portal_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Configuration Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Configuration Circuit Breaker détaillée
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        registerHealthIndicator: true
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - feign.FeignException
    instances:
      studentService:
        baseConfig: default
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      courseService:
        baseConfig: default
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - feign.FeignException.ServiceUnavailable
    instances:
      studentService:
        baseConfig: default
      courseService:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      studentService:
        baseConfig: default
      courseService:
        baseConfig: default

# Logging
logging:
  level:
    io.github.resilience4j: DEBUG