server:
  port: 8084

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Configuration JWT
jwt:
  secret: education-platform-secret-key-2024-very-secure-and-long-key-minimum-256-bits
  expiration: 86400000  # 24 heures en millisecondes
  refresh-expiration: 604800000  # 7 jours

# Configuration sécurité
security:
  public-endpoints:
    - /api/auth/login
    - /api/auth/register
    - /actuator/health